### ISSUE TITLE
Player cancels and still gets reward

### ISSUE THREAD

**Issue by NobodyDeveloper** [Serrulata-Studios/serrulata-atmrobbery#1]
Player is able to cancel the progress bar of "grabbing money" after successfully doing the hack and still receives the reward if doing so.

**Comment by AngryMaximus** [comment]
Confirmed still the case, if you figured out how to prevent this, let me know

**Comment by Cuzzman** [comment]
Check latest Pull request, Possible Fix. Unsure since i could not test

**Comment by MoneSuper** [comment]
#3 Scripts has been updated sorry for the long wait!
